In [1]:
import pandas as pd
import numpy as np
import ast

In [2]:
movies = pd.read_csv(r'dataset.csv')

In [3]:
movies

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221

In [4]:
movies.isna().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

In [5]:
movies.dropna(ignore_index = True , inplace = True)

In [6]:
movies

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811
...,...,...,...,...,...,...,...,...,...
9980,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347
9981,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417
9982,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332
9983,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668
9984,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221

In [7]:
movies['overview'][9981]

'The sharks take bite out of the East Coast when the sharknado hits Washington, D.C. and Orlando, Florida.'

In [8]:
movies['title'][99]

'Everything Everywhere All at Once'

In [9]:
movies['tags'] = movies['genre'] + movies['overview']

In [10]:
movies.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count,tags
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862,"Drama,CrimeFramed in the 1940s for the double ..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731,"Comedy,Drama,RomanceRaj is a rich, carefree, h..."
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280,"Drama,CrimeSpanning the years 1945 to 1955, a ..."
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959,"Drama,History,WarThe true story of how busines..."
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811,"Drama,CrimeIn the continuing saga of the Corle..."

In [11]:
df = movies[['id' , 'title' , 'tags']].copy()

In [12]:
df.head()

,id,title,tags
0,278,The Shawshank Redemption,"Drama,CrimeFramed in the 1940s for the double ..."
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,RomanceRaj is a rich, carefree, h..."
2,238,The Godfather,"Drama,CrimeSpanning the years 1945 to 1955, a ..."
3,424,Schindler's List,"Drama,History,WarThe true story of how busines..."
4,240,The Godfather: Part II,"Drama,CrimeIn the continuing saga of the Corle..."

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
cv = CountVectorizer(max_features = 10000 , stop_words = 'english')

In [15]:
X = cv.fit_transform(df['tags']).toarray()

In [16]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [17]:
X.shape

(9985, 10000)

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

In [19]:
sim = cosine_similarity(X)

In [20]:
sim

array([[1.        , 0.06253054, 0.05802589, ..., 0.07963978, 0.07597372,
        0.03481553],
       [0.06253054, 1.        , 0.08980265, ..., 0.        , 0.        ,
        0.        ],
       [0.05802589, 0.08980265, 1.        , ..., 0.02541643, 0.03636965,
        0.        ],
       ...,
       [0.07963978, 0.        , 0.02541643, ..., 1.        , 0.03327792,
        0.03049971],
       [0.07597372, 0.        , 0.03636965, ..., 0.03327792, 1.        ,
        0.04364358],
       [0.03481553, 0.        , 0.        , ..., 0.03049971, 0.04364358,
        1.        ]])

In [64]:
dist = sorted(list(enumerate(sim[0])), key=lambda X: X[1], reverse=True)
#returns a list as (index , similarity) as 1 element
#sim[0] means similarity to the movie at index 0

In [72]:
dist

[(0, 0.9999999999999999),
 (3708, 0.23539595453459985),
 (9000, 0.22613350843332275),
 (3648, 0.22019275302527214),
 (2605, 0.20100756305184245),
 (4067, 0.20100756305184245),
 (6154, 0.20100756305184245),
 (698, 0.19894589252079756),
 (7321, 0.1976738731537168),
 (1009, 0.1939524551505708),
 (884, 0.1899342940993966),
 (7268, 0.1899342940993966),
 (2963, 0.18802535827258876),
 (7475, 0.1877810107252081),
 (2991, 0.1860968420796942),
 (715, 0.18582615562066462),
 (9512, 0.18148850216015694),
 (2120, 0.17978662999019787),
 (4199, 0.17912443020795962),
 (9709, 0.17766726362967541),
 (4293, 0.17407765595569785),
 (4488, 0.17407765595569785),
 (4489, 0.17407765595569785),
 (5426, 0.17170914210964275),
 (9133, 0.17063023229633048),
 (2081, 0.16888013236829966),
 (4062, 0.16888013236829966),
 (4220, 0.16888013236829966),
 (6756, 0.16888013236829966),
 (7415, 0.16888013236829966),
 (7468, 0.16888013236829966),
 (2796, 0.16888013236829963),
 (531, 0.16514456476895412),
 (725, 0.16514456476895412),
 (791, 0.16514456476895412),
 (2225, 0.16514456476895412),
 (3159, 0.16514456476895412),
 (393, 0.1651445647689541),
 (1068, 0.16448792373994225),
 (2925, 0.16412198797244368),
 (2927, 0.16412198797244368),
 (7555, 0.16412198797244368),
 (1038, 0.15974461276617435),
 (6400, 0.15974461276617435),
 (7880, 0.15974461276617435),
 (9747, 0.15974461276617435),
 (1175, 0.1592795619605697),
 (2583, 0.15891043154093204),
 (663, 0.15745916432444343),
 (2626, 0.1574591643244434),
 (1507, 0.15632634987018063),
 (4940, 0.15632634987018063),
 (1264, 0.15569978883230462),
 (1619, 0.1556997888323046),
 (3832, 0.1556997888323046),
 (9467, 0.1556997888323046),
 (5585, 0.15399810070180361),
 (645, 0.15386436372416593),
 (2009, 0.15386436372416593),
 (4232, 0.15386436372416593),
 (5774, 0.15386436372416593),
 (7874, 0.15386436372416593),
 (1646, 0.1523510148357077),
 (1480, 0.1519474352795173),
 (2084, 0.1519474352795173),
 (6295, 0.1519474352795173),
 (4153, 0.15151515151515155),
 (3847, 0.15075567228888184),
 (4809, 0.15075567228888184),
 (4986, 0.15075567228888184),
 (5025, 0.15075567228888184),
 (8405, 0.15075567228888184),
 (8826, 0.15075567228888184),
 (87, 0.14927035850663303),
 (196, 0.14927035850663303),
 (279, 0.14927035850663303),
 (8258, 0.14927035850663303),
 (3182, 0.1484539238050411),
 (4085, 0.1484539238050411),
 (6292, 0.1484539238050411),
 (8665, 0.14770978917519928),
 (441, 0.14712247158412492),
 (1544, 0.14712247158412492),
 (6160, 0.14712247158412492),
 (7917, 0.14712247158412492),
 (933, 0.14519080172812557),
 (2112, 0.14519080172812557),
 (3250, 0.14519080172812557),
 (7824, 0.14519080172812557),
 (7768, 0.14506471329641488),
 (9966, 0.14506471329641488),
 (1223, 0.1448413648755803),
 (4985, 0.1448413648755803),
 (5260, 0.1448413648755803),
 (5510, 0.1448413648755803),
 (5555, 0.1448413648755803),
 (7046, 0.1448413648755803),
 (6091, 0.1444080962863686),
 (4063, 0.1436067394758882),
 (6536, 0.14309095175803563),
 (5880, 0.14213381090374033),
 (4404, 0.1411956236812263),
 (9120, 0.14119562368122626),
 (331, 0.13957263155977065),
 (989, 0.13957263155977065),
 (1516, 0.13957263155977065),
 (4294, 0.13957263155977065),
 (8081, 0.13957263155977065),
 (6860, 0.13937366833451514),
 (1191, 0.1392621247645583),
 (8025, 0.1392621247645583),
 (6416, 0.13762047064079508),
 (6559, 0.13762047064079508),
 (5180, 0.1365577483997838),
 (7596, 0.1365577483997838),
 (7867, 0.1359318119567592),
 (52, 0.13483997249264842),
 (71, 0.1348399724926484),
 (143, 0.1348399724926484),
 (170, 0.1348399724926484),
 (1407, 0.1348399724926484),
 (2862, 0.1348399724926484),
 (2932, 0.1348399724926484),
 (3761, 0.1348399724926484),
 (6561, 0.1348399724926484),
 (6754, 0.1348399724926484),
 (7132, 0.1348399724926484),
 (9269, 0.1348399724926484),
 (5506, 0.1343038273375634),
 (3880, 0.13400504203456162),
 (4630, 0.13400504203456162),
 (5549, 0.13400504203456162),
 (6072, 0.13400504203456162),
 (8066, 0.13400504203456162),
 (8754, 0.13273296830047474),
 (2529, 0.1315903389919538),
 (3233, 0.1315903389919538),
 (4951, 0.1315903389919538),
 (5858, 0.1315903389919538),
 (7392, 0.1315903389919538),
 (9571, 0.1315903389919538),
 (295, 0.1305582419667734),
 (729, 0.1305582419667734),
 (1573, 0.1305582419667734),
 (2335, 0.1305582419667734),
 (2813, 0.1305582419667734),
 (3349, 0.1305582419667734),
 (3892, 0.1305582419667734),
 (4345, 0.1305582419667734),
 (4483, 0.1305582419667734),
 (4650, 0.1305582419667734),
 (6456, 0.1305582419667734),
 (6537, 0.1305582419667734),
 (6744, 0.1305582419667734),
 (7389, 0.1305582419667734),
 (9508, 0.1305582419667734),
 (834, 0.1297498240269205),
 (6282, 0.1297498240269205),
 (6848, 0.1297498240269205),
 (1599, 0.1293016367670472),
 (4271, 0.12833175058483634),
 (1193, 0.12712834523274563),
 (2011, 0.12712834523274563),
 (2936, 0.12712834523274563),
 (3042, 0.12712834523274563),
 (7541, 0.12712834523274563),
 (8534, 0.12712834523274563),
 (4903, 0.12695917902975642),
 (7674, 0.12695917902975642),
 (2209, 0.12666009927622474),
 (2500, 0.12666009927622474),
 (3164, 0.12666009927622474),
 (3242, 0.12666009927622474),
 (3359, 0.12666009927622474),
 (4051, 0.12666009927622474),
 (4401, 0.12666009927622474),
 (5288, 0.12666009927622474),
 (5392, 0.12666009927622474),
 (5841, 0.12666009927622474),
 (6325, 0.12666009927622474),
 (6681, 0.12666009927622474),
 (7988, 0.12666009927622474),
 (8110, 0.12666009927622474),
 (8201, 0.12666009927622474),
 (8269, 0.12666009927622474),
 (8794, 0.12666009927622474),
 (8911, 0.12666009927622474),
 (9808, 0.12666009927622474),
 (6275, 0.12562972690740154),
 (9757, 0.12562972690740154),
 (2712, 0.1250610798961445),
 (7530, 0.1250610798961445),
 (7753, 0.1250610798961445),
 (4070, 0.12434118282549846),
 (2028, 0.12395530151376132),
 (919, 0.12309149097933275),
 (1120, 0.12309149097933275),
 (1145, 0.12309149097933275),
 (2219, 0.12309149097933275),
 (2330, 0.12309149097933275),
 (4376, 0.12309149097933275),
 (6457, 0.12309149097933275),
 (7437, 0.12309149097933275),
 (8261, 0.12309149097933275),
 (501, 0.12309149097933274),
 (1447, 0.12309149097933274),
 (2786, 0.12309149097933274),
 (3507, 0.12309149097933274),
 (3616, 0.12309149097933274),
 (5117, 0.12309149097933274),
 (6890, 0.12309149097933274),
 (7163, 0.12309149097933274),
 (159, 0.12309149097933272),
 (6252, 0.12187873735452177),
 (313, 0.12121212121212123),
 (3788, 0.12121212121212123),
 (7150, 0.12121212121212123),
 (138, 0.11980845957463077),
 (552, 0.11980845957463077),
 (955, 0.11980845957463077),
 (1105, 0.11980845957463077),
 (1976, 0.11980845957463077),
 (2136, 0.11980845957463077),
 (2392, 0.11980845957463077),
 (3026, 0.11980845957463077),
 (3187, 0.11980845957463077),
 (3296, 0.11980845957463077),
 (3412, 0.11980845957463077),
 (3506, 0.11980845957463077),
 (3883, 0.11980845957463077),
 (5255, 0.11980845957463077),
 (5432, 0.11980845957463077),
 (5523, 0.11980845957463077),
 (5698, 0.11980845957463077),
 (7252, 0.11980845957463077),
 (7806, 0.11980845957463077),
 (8080, 0.11980845957463077),
 (8498, 0.11980845957463077),
 (9579, 0.11980845957463077),
 (3905, 0.11955702496470261),
 (747, 0.11941628680530642),
 (2695, 0.11941628680530642),
 (2945, 0.1185477931931699),
 (6797, 0.11844484241978359),
 (1287, 0.11769797726729994),
 (168, 0.11769797726729993),
 (1537, 0.11769797726729993),
 (4375, 0.11769797726729993),
 (6241, 0.11769797726729993),
 (8346, 0.11769797726729993),
 (408, 0.11736313170325507),
 (3292, 0.11736313170325507),
 (4076, 0.11736313170325507),
 (9356, 0.11736313170325507),
 (1542, 0.11677484162422845),
 (2106, 0.11677484162422845),
 (2230, 0.11677484162422845),
 (2522, 0.11677484162422845),
 (2659, 0.11677484162422845),
 (2726, 0.11677484162422845),
 (3452, 0.11677484162422845),
 (3620, 0.11677484162422845),
 (4022, 0.11677484162422845),
 (4140, 0.11677484162422845),
 (4298, 0.11677484162422845),
 (4300, 0.11677484162422845),
 (4765, 0.11677484162422845),
 (5726, 0.11677484162422845),
 (6751, 0.11677484162422845),
 (7408, 0.11677484162422845),
 (7847, 0.11677484162422845),
 (841, 0.1160517706371319),
 (1477, 0.1160517706371319),
 (1754, 0.1160517706371319),
 (3455, 0.1160517706371319),
 (3669, 0.1160517706371319),
 (4269, 0.1160517706371319),
 (6968, 0.1160517706371319),
 (7322, 0.1160517706371319),
 (7502, 0.1144727614064285),
 (8532, 0.1144727614064285),
 (8632, 0.1144727614064285),
 (6230, 0.11428758022062362),
 (8634, 0.1142875802206236),
 (819, 0.11396057645963796),
 (1034, 0.11396057645963796),
 (1489, 0.11396057645963796),
 (1657, 0.11396057645963796),
 (2160, 0.11396057645963796),
 (2453, 0.11396057645963796),
 (3234, 0.11396057645963796),
 (3936, 0.11396057645963796),
 (5682, 0.11396057645963796),
 (7320, 0.11396057645963796),
 (7763, 0.11396057645963796),
 (8237, 0.11396057645963796),
 (8308, 0.11396057645963796),
 (8929, 0.11396057645963796),
 (9132, 0.11396057645963796),
 (2966, 0.11295649894498101),
 (2352, 0.11236664374387367),
 (1918, 0.11149893466761211),
 (4460, 0.11149893466761211),
 (6306, 0.11149893466761211),
 (7073, 0.11149893466761211),
 (252, 0.11134044285378082),
 (1449, 0.11134044285378082),
 (1625, 0.11134044285378082),
 (1775, 0.11134044285378082),
 (1958, 0.11134044285378082),
 (1970, 0.11134044285378082),
 (2148, 0.11134044285378082),
 (3513, 0.11134044285378082),
 (3610, 0.11134044285378082),
 (3982, 0.11134044285378082),
 (4567, 0.11134044285378082),
 (4618, 0.11134044285378082),
 (5454, 0.11134044285378082),
 (7078, 0.11134044285378082),
 (9660, 0.11134044285378082),
 (5087, 0.11009637651263608),
 (5222, 0.11009637651263608),
 (6820, 0.11009637651263608),
 (7242, 0.11009637651263608),
 (456, 0.11009637651263607),
 (865, 0.11009637651263607),
 (1822, 0.11009637651263607),
 (2238, 0.11009637651263607),
 (3473, 0.11009637651263607),
 (4328, 0.11009637651263607),
 (4588, 0.11009637651263607),
 (4848, 0.11009637651263607),
 (4893, 0.11009637651263607),
 (6694, 0.11009637651263607),
 (278, 0.10889310129609417),
 (547, 0.10889310129609417),
 (869, 0.10889310129609417),
 (960, 0.10889310129609417),
 (976, 0.10889310129609417),
 (1993, 0.10889310129609417),
 (2426, 0.10889310129609417),
 (2472, 0.10889310129609417),
 (3599, 0.10889310129609417),
 (4883, 0.10889310129609417),
 (8123, 0.10889310129609417),
 (8549, 0.10889310129609417),
 (2654, 0.10874544956540738),
 (3277, 0.10874544956540738),
 (7404, 0.10874544956540738),
 (7789, 0.10874544956540738),
 (336, 0.10744306187005072),
 (541, 0.10744306187005072),
 (1430, 0.10744306187005072),
 (3269, 0.10744306187005072),
 (3536, 0.10744306187005072),
 (5983, 0.10744306187005072),
 (8244, 0.10744306187005072),
 (511, 0.10660035817780525),
 (1298, 0.10660035817780525),
 (1881, 0.10660035817780525),
 (2164, 0.10660035817780525),
 (3457, 0.10660035817780525),
 (4077, 0.10660035817780525),
 (4221, 0.10660035817780525),
 (4606, 0.10660035817780525),
 (4687, 0.10660035817780525),
 (4892, 0.10660035817780525),
 (5673, 0.10660035817780525),
 (5906, 0.10660035817780525),
 (5945, 0.10660035817780525),
 (6173, 0.10660035817780525),
 (6714, 0.10660035817780525),
 (6971, 0.10660035817780525),
 (9167, 0.10660035817780525),
 (9390, 0.10660035817780525),
 (671, 0.10618637464037979),
 (8749, 0.10618637464037979),
 (9736, 0.10618637464037979),
 (36, 0.10497277621629561),
 (190, 0.10497277621629561),
 (322, 0.10497277621629561),
 (470, 0.10497277621629561),
 (991, 0.10497277621629561),
 (1349, 0.10497277621629561),
 (1533, 0.10497277621629561),
 (1636, 0.10497277621629561),
 (1988, 0.10497277621629561),
 (2766, 0.10497277621629561),
 (2856, 0.10497277621629561),
 (3013, 0.10497277621629561),
 (3364, 0.10497277621629561),
 (4393, 0.10497277621629561),
 (6335, 0.10497277621629561),
 (6430, 0.10497277621629561),
 (9107, 0.10497277621629561),
 (5174, 0.1049727762162956),
 (5408, 0.1049727762162956),
 (825, 0.10444659357341872),
 (1039, 0.10444659357341872),
 (1834, 0.10444659357341872),
 (3263, 0.10444659357341872),
 (5295, 0.10444659357341872),
 (5963, 0.10444659357341872),
 (6260, 0.10444659357341872),
 (8741, 0.10444659357341872),
 (2353, 0.10379985922153641),
 (3033, 0.10379985922153641),
 (7849, 0.10379985922153641),
 (8835, 0.10379985922153641),
 (2568, 0.10266540046786908),
 (5874, 0.10266540046786908),
 (8163, 0.10266540046786908),
 (6961, 0.1025762424827773),
 (28, 0.10241831129983785),
 (70, 0.10241831129983785),
 (608, 0.10241831129983785),
 (731, 0.10241831129983785),
 (1133, 0.10241831129983785),
 (1853, 0.10241831129983785),
 (2673, 0.10241831129983785),
 (4532, 0.10241831129983785),
 (4560, 0.10241831129983785),
 (6525, 0.10241831129983785),
 (6529, 0.10241831129983785),
 (7000, 0.10241831129983785),
 (7193, 0.10241831129983785),
 (9071, 0.10241831129983785),
 (9118, 0.10241831129983785),
 (6760, 0.10187124277134103),
 (4510, 0.10156734322380513),
 (50, 0.10050378152592122),
 (437, 0.10050378152592122),
 (793, 0.10050378152592122),
 (839, 0.10050378152592122),
 (903, 0.10050378152592122),
 (1016, 0.10050378152592122),
 (1201, 0.10050378152592122),
 (1216, 0.10050378152592122),
 (1258, 0.10050378152592122),
 (1773, 0.10050378152592122),
 (1830, 0.10050378152592122),
 (1954, 0.10050378152592122),
 (1956, 0.10050378152592122),
 (2049, 0.10050378152592122),
 (2050, 0.10050378152592122),
 (2169, 0.10050378152592122),
 (2228, 0.10050378152592122),
 (2306, 0.10050378152592122),
 (2362, 0.10050378152592122),
 (2412, 0.10050378152592122),
 (2462, 0.10050378152592122),
 (2616, 0.10050378152592122),
 (2758, 0.10050378152592122),
 (2853, 0.10050378152592122),
 (2907, 0.10050378152592122),
 (3108, 0.10050378152592122),
 (3492, 0.10050378152592122),
 (3644, 0.10050378152592122),
 (3689, 0.10050378152592122),
 (3755, 0.10050378152592122),
 (3882, 0.10050378152592122),
 (4846, 0.10050378152592122),
 (5173, 0.10050378152592122),
 (5191, 0.10050378152592122),
 (5674, 0.10050378152592122),
 (5971, 0.10050378152592122),
 (6277, 0.10050378152592122),
 (6605, 0.10050378152592122),
 (6963, 0.10050378152592122),
 (6987, 0.10050378152592122),
 (7068, 0.10050378152592122),
 (7540, 0.10050378152592122),
 (8292, 0.10050378152592122),
 (8394, 0.10050378152592122),
 (8631, 0.10050378152592122),
 (8681, 0.10050378152592122),
 (9485, 0.10050378152592122),
 (9794, 0.10050378152592122),
 (1659, 0.09947294626039876),
 (7347, 0.09947294626039876),
 (7387, 0.09947294626039876),
 (344, 0.09869275424396534),
 (3268, 0.09869275424396534),
 (4882, 0.09869275424396534),
 (5164, 0.09869275424396534),
 (6753, 0.09869275424396534),
 (6902, 0.09869275424396534),
 (8557, 0.09869275424396534),
 (8640, 0.09869275424396534),
 (8816, 0.09869275424396534),
 (8902, 0.09869275424396534),
 (8983, 0.09855206599818044),
 (2310, 0.09847319278346618),
 (3963, 0.09847319278346618),
 (4665, 0.09847319278346618),
 (5697, 0.09750298988361743),
 (164, 0.0969762275752854),
 (208, 0.0969762275752854),
 (600, 0.0969762275752854),
 (790, 0.0969762275752854),
 (1672, 0.0969762275752854),
 (2405, 0.0969762275752854),
 (2656, 0.0969762275752854),
 (3130, 0.0969762275752854),
 (3314, 0.0969762275752854),
 (3417, 0.0969762275752854),
 (3663, 0.0969762275752854),
 (3840, 0.0969762275752854),
 (4049, 0.0969762275752854),
 (4561, 0.0969762275752854),
 (7937, 0.0969762275752854),
 (156, 0.09656090991705353),
 (535, 0.09656090991705353),
 (773, 0.09656090991705353),
 (794, 0.09656090991705353),
 (795, 0.09656090991705353),
 (886, 0.09656090991705353),
 (1056, 0.09656090991705353),
 (1060, 0.09656090991705353),
 (1362, 0.09656090991705353),
 (1858, 0.09656090991705353),
 (1924, 0.09656090991705353),
 (2325, 0.09656090991705353),
 (2411, 0.09656090991705353),
 (2675, 0.09656090991705353),
 (2833, 0.09656090991705353),
 (2916, 0.09656090991705353),
 (2980, 0.09656090991705353),
 (3041, 0.09656090991705353),
 (3148, 0.09656090991705353),
 (4386, 0.09656090991705353),
 (4435, 0.09656090991705353),
 (4616, 0.09656090991705353),
 (4856, 0.09656090991705353),
 (5844, 0.09656090991705353),
 (5981, 0.09656090991705353),
 (6662, 0.09656090991705353),
 (7002, 0.09656090991705353),
 (7638, 0.09656090991705353),
 (7796, 0.09656090991705353),
 (8157, 0.09656090991705353),
 (8225, 0.09656090991705353),
 (8278, 0.09656090991705353),
 (8320, 0.09656090991705353),
 (8369, 0.09656090991705353),
 (8531, 0.09656090991705353),
 (9376, 0.09656090991705353),
 (9383, 0.09656090991705353),
 (9637, 0.09656090991705353),
 (2239, 0.09564561997176209),
 (3075, 0.09564561997176209),
 (1114, 0.09553752543358544),
 (140, 0.09534625892455922),
 (994, 0.09534625892455922),
 (1787, 0.09534625892455922),
 (2070, 0.09534625892455922),
 (2585, 0.09534625892455922),
 (2677, 0.09534625892455922),
 (3086, 0.09534625892455922),
 (3802, 0.09534625892455922),
 (4824, 0.09534625892455922),
 (5046, 0.09534625892455922),
 (5590, 0.09534625892455922),
 (6327, 0.09534625892455922),
 (6349, 0.09534625892455922),
 (9324, 0.09534625892455922),
 (2274, 0.09475587393582686),
 (4270, 0.09475587393582686),
 (6783, 0.09475587393582686),
 (7135, 0.09456150270769186),
 (5793, 0.09385638197228473),
 (38, 0.09379580992210838),
 (477, 0.09379580992210838),
 (848, 0.09379580992210838),
 (878, 0.09379580992210838),
 (1286, 0.09379580992210838),
 (2300, 0.09379580992210838),
 (2662, 0.09379580992210838),
 (3012, 0.09379580992210838),
 (3052, 0.09379580992210838),
 (3744, 0.09379580992210838),
 (5601, 0.09379580992210838),
 (6698, 0.09379580992210838),
 (7338, 0.09379580992210838),
 (8891, 0.09379580992210838),
 (9692, 0.09379580992210838),
 (80, 0.0930484210398471),
 (175, 0.0930484210398471),
 (293, 0.0930484210398471),
 (554, 0.0930484210398471),
 (876, 0.0930484210398471),
 (902, 0.0930484210398471),
 (1052, 0.0930484210398471),
 (1421, 0.0930484210398471),
 (1456, 0.0930484210398471),
 (1996, 0.0930484210398471),
 (2294, 0.0930484210398471),
 (2332, 0.0930484210398471),
 (2388, 0.0930484210398471),
 (2587, 0.0930484210398471),
 (2784, 0.0930484210398471),
 (2785, 0.0930484210398471),
 (2948, 0.0930484210398471),
 (2979, 0.0930484210398471),
 (3516, 0.0930484210398471),
 (3794, 0.0930484210398471),
 (3830, 0.0930484210398471),
 (3925, 0.0930484210398471),
 (4005, 0.0930484210398471),
 (4183, 0.0930484210398471),
 (4225, 0.0930484210398471),
 (4722, 0.0930484210398471),
 (4959, 0.0930484210398471),
 (4969, 0.0930484210398471),
 (5013, 0.0930484210398471),
 (5166, 0.0930484210398471),
 (5225, 0.0930484210398471),
 (5595, 0.0930484210398471),
 (5676, 0.0930484210398471),
 (5731, 0.0930484210398471),
 (5973, 0.0930484210398471),
 (6465, 0.0930484210398471),
 (6531, 0.0930484210398471),
 (6632, 0.0930484210398471),
 (6921, 0.0930484210398471),
 (7748, 0.0930484210398471),
 (7877, 0.0930484210398471),
 (8001, 0.0930484210398471),
 (8101, 0.0930484210398471),
 (8140, 0.0930484210398471),
 (8341, 0.0930484210398471),
 (8372, 0.0930484210398471),
 (8401, 0.0930484210398471),
 (8524, 0.0930484210398471),
 (8856, 0.0930484210398471),
 (8908, 0.0930484210398471),
 (9076, 0.0930484210398471),
 (9150, 0.0930484210398471),
 (9218, 0.0930484210398471),
 (9548, 0.0930484210398471),
 (9869, 0.0930484210398471),
 (9975, 0.0930484210398471),
 (13, 0.09231861823449955),
 (222, 0.09231861823449955),
 (542, 0.09231861823449955),
 (617, 0.09231861823449955),
 (1291, 0.09231861823449955),
 (1910, 0.09231861823449955),
 (1921, 0.09231861823449955),
 (2851, 0.09231861823449955),
 (5519, 0.09231861823449955),
 (6833, 0.09231861823449955),
 (8165, 0.09231861823449955),
 (8793, 0.09231861823449955),
 (9216, 0.09222859518214331),
 (8513, 0.0922285951821433),
 (2001, 0.09124148357522649),
 (718, 0.09090909090909093),
 (3050, 0.09090909090909093),
 (3724, 0.09090909090909093),
 (4482, 0.09090909090909093),
 (4812, 0.09090909090909093),
 (4895, 0.09090909090909093),
 (5375, 0.09090909090909093),
 (5539, 0.09090909090909093),
 (5992, 0.09090909090909093),
 (7057, 0.09090909090909093),
 (7359, 0.09090909090909093),
 (7570, 0.09090909090909093),
 (8374, 0.09090909090909093),
 (8819, 0.09090909090909093),
 (9421, 0.09090909090909093),
 (1570, 0.0902550601789804),
 (77, 0.08989331499509894),
 (311, 0.08989331499509894),

In [74]:
for i in dist[0:5]:
    print(df.iloc[i[0]].title)

The Shawshank Redemption
Anything for Her
The Getaway
The Woodsman
Pusher II

In [100]:
def recommend(movie):
    index = df[df['title'] == movie].index[0]
    rec = []
    _dist = sorted(list(enumerate(sim[index])), reverse=True, key=lambda X: X[1])
    for i in _dist[1:6]:
        rec.append(df.iloc[i[0]].title)
    return rec

In [104]:
recommend('Dilwale Dulhania Le Jayenge')

['The Cheetah Girls: One World',
 'A Passage to India',
 'Fatal Attraction',
 'Noelle',
 'Just Married']

In [112]:
import pickle
# Save the similarity matrix
with open('similarity.pkl', 'wb') as f:
    pickle.dump(sim, f)

# Save the dataframe 
with open('movies.pkl', 'wb') as f:
    pickle.dump(df, f)

#Save the vectorizer 
with open('vectorizer.pkl', 'wb') as f:
    pickle.dump(cv, f)